import express from "express";
import { getAllCoding,getDateCoding,insertCoding,deleteCoding, updateCoding, updateQuestions } from "../controllers/coding-controller.js";
const router=express.Router();
router.get("/all",getAllCoding);
router.get("/:id",getDateCoding);
router.post("/insert",insertCoding);
router.put("/update/:id",updateCoding);
router.put("/updatequestions/:id",updateQuestions);
router.delete("/delete",deleteCoding);
export default router;